const mockEvents = 
{
  "city": 
  {
    "id": 1007700,
    "city": "München",
    "lat": 48.14,
    "lon": 11.58,
    "state": "",
    "country": "de",
    "zip": "meetup3",
    "member_count": 1257
  },
  "events": 
  [
    {
      "created": 1581676443000,
      "duration": 5400000,
      "id": "268705764",
      "name": "Running Kubernetes on Azure",
      "rsvp_limit": 80,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583429400000,
      "local_date": "2020-03-05",
      "local_time": "18:30",
      "updated": 1581927279000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 42,
      "venue": {
        "id": 25766821,
        "name": "medialesson - Büro München",
        "lat": 48.153099060058594,
        "lon": 11.583580017089844,
        "repinned": true,
        "address_1": "Leopoldstr. 8-10",
        "address_2": "c/o Nutrion Coworking Space",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1520252901000,
        "name": "Software, Technology & Design Meetup München",
        "id": 27731423,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Software-Technology-Meetup-Munchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Software-Technology-Meetup-Munchen/events/268705764/",
      "description": "<p>In this session Mohit Chhabra will give you insights how to run real apps on the most popular container orchestrator in Azure.</p> <p>We’ll review a high-level overview of the Azure Kubernetes Service (AKS) service and Azure Container Registry (ACR). We will start with the basic concepts of Kubernetes followed by understanding how AKS is different from the vanilla Kubernetes. Finally we'll be setting up and deploying a real world app on AKS. Feel free to follow along!</p> <p>Our speaker Mohit is working as Software Engineer at medialesson GmbH, Germany. He is currently Microsoft Most Valuable Professional for Microsoft Azure and former leader of BDotnet (India's Biggest offline community). He has delivered more than 50 sessions in the community and international conferences. Prior to this, Mohit was Microsoft Student Partner and Mozilla Student Representative. He was also India's first Azure Champion and the first person to intern in Microsoft Technology Center.</p> <p>This meetup will be hosted by medialesson, food and drinks will be provided. The session language is English. Please make sure you update your RSVP status 24h in advance so we don't waste any food!</p> ",
      "how_to_find_us": "The entry to building No. 8 is directly accessible from Leopoldstr. near Siegestor, walk down the broad spiral stairs down to the basement and enter trough the first glass door on the right hand.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1579787657000,
      "duration": 10800000,
      "id": "268140184",
      "name": "Munich Accessibility Meetup #6",
      "rsvp_limit": 120,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583343000000,
      "local_date": "2020-03-04",
      "local_time": "18:30",
      "updated": 1581945653000,
      "utc_offset": 3600000,
      "waitlist_count": 5,
      "yes_rsvp_count": 120,
      "venue": {
        "id": 26112492,
        "name": "Google",
        "lat": 48.14295959472656,
        "lon": 11.54114818572998,
        "repinned": true,
        "address_1": "Erika-Mann-Straße 33",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1539067167000,
        "name": "Munich Accessibility Meetup",
        "id": 30155727,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munich-Accessibility-Meetup",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munich-Accessibility-Meetup/events/268140184/",
      "description": "<p>Dear friends,<br/>2020 is already on its way, so time to catch up with another Munich Accessibility Meetup!</p> <p>*** Agenda 📅 ***<br/>18:30 Doors open + food + mingle<br/>19:00 Talk 1:",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581937808000,
      "duration": 10800000,
      "id": "268771520",
      "name": "Save the date - Design Thinking Meetup",
      "rsvp_limit": 4,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1588091400000,
      "local_date": "2020-04-28",
      "local_time": "18:30",
      "rsvp_open_offset": "PT177H30M",
      "updated": 1581943034000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 4,
      "group": {
        "created": 1460553553000,
        "name": "Design Thinking München",
        "id": 19836170,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "DT-Muc",
        "who": "Design Thinkers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/DT-Muc/events/268771520/",
      "description": "<p>Save the date for our next DT Meetup!</p> <p>If you are interested to host the next meetup, just drop us a message.</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581637409000,
      "duration": 10800000,
      "id": "268694342",
      "name": "Unternehmertreffen & Start up-Event in München",
      "rsvp_limit": 30,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1586102400000,
      "local_date": "2020-04-05",
      "local_time": "18:00",
      "updated": 1581975365000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 28,
      "venue": {
        "id": 26865352,
        "name": "The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München",
        "lat": 48.128822326660156,
        "lon": 11.574684143066406,
        "repinned": false,
        "address_1": "Frauenhoferstraße 32, 80469 München",
        "city": "München",
        "country": "DE",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1581635431000,
        "name": "Unternehmertreffen and Start up-Event ",
        "id": 33341612,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Unternehmertreffen-Start-up-Event-Munchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694342/",
      "description": "<p>DAS UNTERNEHMERTREFFEN „MÜNCHEN“ STARTUP EVENT</p> <p>INVESTOREN / BUSINESS-ANGEL*<br/>*mehr Details in der Beschreibung</p> <p>Das Unternehmertreffen Munich-Milan ist das Forum für Geschäftsfreunde in ganz Deutschland. Wir hören gemeinsam spannende Vorträge, veranstalten Aktionen, haben Zeit für informelle Gespräche und bahnen Geschäfte an.</p> <p>Wir sind überparteilich und unabhängig. Und vor allem: Wir haben viel Spaß am Netzwerken!</p> <p>Zahlreiche UNTERNEHMER und STARTUP UNTERNEHMEN aus dem Raum München nehmen teil und freuen sich über Jeden, der unser Netzwerk weiter verstärkt. AUCH STUDENTEN MIT GUTEN IDEEN SIND HERZLICH WILLKOMMEN.</p> <p>Informationen und Tickets finden sich unter: ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581324523000,
      "duration": 5400000,
      "id": "268599428",
      "name": "First kick-off event",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1582822800000,
      "local_date": "2020-02-27",
      "local_time": "18:00",
      "updated": 1582007414000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 34,
      "venue": {
        "id": 26866738,
        "name": "Carl ZEISS Digital Innovation Partner",
        "lat": 48.09576416015625,
        "lon": 11.525047302246094,
        "repinned": false,
        "address_1": "Kistlerhofstraße 70",
        "address_2": "Building 160, 4th floor ",
        "city": "München ",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1573128374000,
        "name": "Microfrontends",
        "id": 32986964,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Microfrontends",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Microfrontends/events/268599428/",
      "description": "<p>Dear Microfrontend friends,<br/>The time has come to organize our first kick-off event! The idea is to have the first one, just as a small get-together event, where I would really love to meet as much of you as possible and to hear more about your microfrontend projects/ideas, but also would like to use the opportunity to talk about the next, real, full-scale meetup event.</p> <p>The location will attach later after I see how many people want to attend, and depending on the interest, it might be a restaurant or might find some other location where we can have more space, in case of bigger interest.</p> <p>Once again short agenda:<br/>- Getting to know each other<br/>- Sharing microfrontend projects/ideas<br/>- Planning next, full-scale, meetup event</p> <p>I'm really excited and looking forward to meeting you all!!</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "local_time": "13:30",
      "local_date": "2020-03-11",
      "link": "https://www.meetup.com/ownyourcareer/events/267960446/",
      "visibility": "public_limited",
      "group": {
        "created": 1469016754000,
        "name": "Own your career development",
        "id": 20204782,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "ownyourcareer",
        "who": "career",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "duration": 10800000,
      "time": 1583929800000,
      "utc_offset": 3600000,
      "name": "Employability & Business Model You - MCBW 2020 Special",
      "id": "267960446"
    },
    {
      "created": 1562151903000,
      "duration": 43200000,
      "id": "262837346",
      "name": "DevCamp - WE PLAY TECH! in München 2020",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1585897200000,
      "local_date": "2020-04-03",
      "local_time": "09:00",
      "updated": 1579080662000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 24,
      "venue": {
        "id": 26813258,
        "name": "Hochschule München - Campus Lothstraße",
        "lat": 48.154300689697266,
        "lon": 11.556997299194336,
        "repinned": false,
        "address_1": "Lothstraße 64",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1501244830000,
        "name": "Tech_Hub München",
        "id": 25186228,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Tech_Hub-Munchen",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Tech_Hub-Munchen/events/262837346/",
      "description": "<p>DevCamp is your platform for developers, computer scientists, IT enthusiasts, and those who want to be became them. DevCamp is a conference with an open agenda about the topics that are moving digital minds in 2020. Make new contacts, connect with experts in a relaxed atmosphere and participate in exciting workshops.</p> <p>At DevCamp, you become a co-creator! All sessions will be chosen upfront by the participants, making everyone an active part of the camp. The event is free of charge and cool prizes are awarded for the best sessions. Be part of a whole experience which seamlessly unites the conference with technology.</p> <p>• What to bring<br/>Prepare a session, if you like to participate as a speaker!</p> <p>• Important to know<br/>Register here:",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1579193914000,
      "duration": 7200000,
      "id": "267965648",
      "name": "World Retro Day 2020 @ Agile Munich",
      "rsvp_limit": 70,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1585157400000,
      "local_date": "2020-03-25",
      "local_time": "18:30",
      "rsvp_open_offset": "PT504H",
      "updated": 1579193914000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26171276,
        "name": "zooplus AG",
        "lat": 48.134639739990234,
        "lon": 11.566325187683105,
        "repinned": true,
        "address_1": "Sonnenstr. 31, 80331 ",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1397242023000,
        "name": "Agile Munich",
        "id": 13860382,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "AgileMunich",
        "who": "Agile Practitioners",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/AgileMunich/events/267965648/",
      "description": "some description",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581340913000,
      "duration": 7200000,
      "fee": {
        "accepts": "paypal",
        "amount": 15,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": true
      },
      "id": "268602542",
      "name": "Structured Creativity #2 - Storytelling Canvas",
      "rsvp_limit": 20,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1584640800000,
      "local_date": "2020-03-19",
      "local_time": "19:00",
      "updated": 1581698506000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 5,
      "venue": {
        "id": 26756901,
        "name": "MUCBOOK CLUBHAUS",
        "lat": 48.138675689697266,
        "lon": 11.561399459838867,
        "repinned": true,
        "address_1": "Schillerstr. 3a (Hinterhof)",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1574928701000,
        "name": "Structured Creativity - Kreativ- und Innovationsmethoden",
        "id": 33055949,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Structured-Creativity-Kreativ-und-Innovationsmethoden",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Structured-Creativity-Kreativ-und-Innovationsmethoden/events/268602542/",
      "description": "<p>#2: Storytelling Canvas<br/>Bei unserem zweiten Treffen am[masked] lernen wir, Storytelling gezielt einzusetzen und werden in einer Übung überzeugende Geschichten entwickeln.</p> <p>Tickets gibt's über Meetup oder Eventbrite:",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1562750055000,
      "duration": 10800000,
      "id": "tkqsdrybcgblb",
      "name": "Designer-Stammtisch",
      "rsvp_limit": 35,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1586365200000,
      "local_date": "2020-04-08",
      "local_time": "19:00",
      "updated": 1562750055000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "venue": {
        "id": 26506448,
        "name": "Cafe Zeitgeist",
        "lat": 48.15114212036133,
        "lon": 11.576687812805176,
        "repinned": false,
        "address_1": "Türkenstraße 74",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1444668795000,
        "name": "Münchner Designer-Stammtisch",
        "id": 19020346,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Designer-Stammtisch",
        "who": "Designer",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Designer-Stammtisch/events/tkqsdrybcgblb/",
      "description": "<p>Liebe DesignerInnen,</p> <p>wir treffen uns jeden 2. Mittwoch im Monat um 19:00 Uhr in (neu:) Zeitgeist in der Türkenstraße.</p> <p>Bringt eure Erfolge, neusten Projekte oder auch kleinen Problemchen mit und teilt sie mit anderen Designern bei einem entspannten Abendessen.</p> <p>Wir freuen uns auf neue Designer und alte Bekannte, und auf einen gemütlichen Abend mit Designer-Kaltsch-und-Tratsch.</p> <p>Lieben Gruß, Ben</p> <p>ps: für alle die gerne länger unterwegs sind finden wir auch diesmal bestimmt wieder eine Location.</p> <p>pps: We mostly chat in German, but English will work just find as well.</p> ",
      "how_to_find_us": "Fragt nach dem Designerstammtisch dort! *** Please ask for the Designerstammtisch there!",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581605836000,
      "duration": 9000000,
      "id": "268682611",
      "name": "TW presents: Lean backends using functional Kotlin",
      "rsvp_limit": 150,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583429400000,
      "local_date": "2020-03-05",
      "local_time": "18:30",
      "updated": 1582532931000,
      "utc_offset": 3600000,
      "waitlist_count": 3,
      "yes_rsvp_count": 150,
      "venue": {
        "id": 25852478,
        "name": "ThoughtWorks Munich ",
        "lat": 48.135501861572266,
        "lon": 11.613557815551758,
        "repinned": true,
        "address_1": "Bothestraße 11",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1413448074000,
        "name": "ThoughtWorks Munich",
        "id": 17658472,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "ThoughtWorks-Muenchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/ThoughtWorks-Muenchen/events/268682611/",
      "description": "<p>Join us for our first meetup in March with our colleagues Srishti and Mario!</p> <p>In this talk we are going to talk about building lean backends in Kotlin, using a functional approach.</p> <p>The language is well suited for this, as it is pragmatic, not afraid of borrowing ideas and has a burgeoning ecosystem. Many talks focus on Android development, but we want to go in the other direction and speak about server side code. Specifically, our focus will be on small services that interact with other services using REST APIs and JSON, in a microservices ecosystem.</p> <p>Kotlin is already quite functional, supporting things like immutability and null safety out of the box. Starting from there we will expand on these and other patterns, like avoiding exceptions and expressing logic as a sequence of transformations, with the help of the excellent Arrow library. We will show code that runs in our production applications that is both elegant and maintainable. You will be able to adopt some of our ideas incrementally and see the benefits for yourself.</p> <p>ABOUT SRISHTI:<br/>Srishti is a software developer and tech enthusiast. She is passionate about clean code, problem-solving, test-driven development, and constantly learning topics that help her to develop quality software.</p> <p>ABOUT MARIO:<br/>Mario develops software for a living. Then he goes home and continues reading about software because he just cannot get enough.<br/>At some point, somebody thought it was a good idea to make him the technical lead of an agile team. He quickly discovered that building things himself is not the same as helping somebody else figure it out.<br/>He learned, somewhat to his surprise, that he really enjoys sharing ideas. According to their feedback, other developers have managed to learn something from Mario. At least they don't tend to run away screaming, which is, as he thinks, a good thing.</p> <p>SNACKS:<br/>As always we are offering various snacks and, beer and soft drinks. No full meal, but something to nibble on.</p> <p>AGENDA:<br/>18:30 Doors open for snacks, drinks and mingle<br/>19:00 Talk and questions<br/>20:00 More questions, drinks and mingle</p> ",
      "how_to_find_us": "The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1562750055000,
      "duration": 10800000,
      "id": "tkqsdrybcfbpb",
      "name": "Designer-Stammtisch",
      "rsvp_limit": 35,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583949600000,
      "local_date": "2020-03-11",
      "local_time": "19:00",
      "updated": 1562750055000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "venue": {
        "id": 26506448,
        "name": "Cafe Zeitgeist",
        "lat": 48.15114212036133,
        "lon": 11.576687812805176,
        "repinned": false,
        "address_1": "Türkenstraße 74",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1444668795000,
        "name": "Münchner Designer-Stammtisch",
        "id": 19020346,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Designer-Stammtisch",
        "who": "Designer",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Designer-Stammtisch/events/tkqsdrybcfbpb/",
      "description": "<p>Liebe DesignerInnen,</p> <p>wir treffen uns jeden 2. Mittwoch im Monat um 19:00 Uhr in (neu:) Zeitgeist in der Türkenstraße.</p> <p>Bringt eure Erfolge, neusten Projekte oder auch kleinen Problemchen mit und teilt sie mit anderen Designern bei einem entspannten Abendessen.</p> <p>Wir freuen uns auf neue Designer und alte Bekannte, und auf einen gemütlichen Abend mit Designer-Kaltsch-und-Tratsch.</p> <p>Lieben Gruß, Ben</p> <p>ps: für alle die gerne länger unterwegs sind finden wir auch diesmal bestimmt wieder eine Location.</p> <p>pps: We mostly chat in German, but English will work just find as well.</p> ",
      "how_to_find_us": "Fragt nach dem Designerstammtisch dort! *** Please ask for the Designerstammtisch there!",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1582037941000,
      "duration": 118800000,
      "fee": {
        "accepts": "paypal",
        "amount": 990,
        "currency": "EUR",
        "description": "",
        "label": "Price",
        "required": true
      },
      "id": "268799734",
      "name": "Workshop: CREATE GREAT EXPERIENCES – Master Lean UX & UI Design",
      "rsvp_limit": 15,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583740800000,
      "local_date": "2020-03-09",
      "local_time": "09:00",
      "updated": 1582038144000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26867169,
        "name": "str84wd Products",
        "lat": 48.14263153076172,
        "lon": 11.545027732849121,
        "repinned": true,
        "address_1": "Erika-Mann-Straße 11",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1480715319000,
        "name": "UX & Product Munich",
        "id": 21366293,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "MunichUX",
        "who": "MUXer",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/MunichUX/events/268799734/",
      "description": "<p>WORKSHOP OVERVIEW</p> <p>You want to design end-to-end user experiences with user research and fast UI prototyping? Learn the right methods and process from an expert with 10+ years real-word design innovation experience.</p> <p>WHO SHOULD ATTEND</p> <p>In previous workshops the graduates had background in online marketing, project management, product management, software development or graphic design. Some of the companies I was running workshops with include companies like: BMW, Roche, Postbank, Munich Re, innogy/eon, ADAC, Viessmann, SinnerSchrader, JvM etc.</p> <p>What they all had in common is they need to:<br/>- Find out what’s really behind UX/UI design<br/>- Learn new customer centric and agile methodologies you can apply in your daily work<br/>- Improve ways to involve customer insights into your product development cycles<br/>- Create more successful products, customers love</p> <p>WHAT IS COVERED</p> <p>Day 1 – Defining the User Experience (UX):<br/>- Conducting initial user research<br/>- Extracting insights from interviews for an early vision<br/>- Defining user segments and map out early functionality<br/>- Creating a user journey<br/>- Communicating our solution with a landing page</p> <p>Day 2 – Designing the User Interface (UI):<br/>- Learning basics of human cognition and psychology<br/>- Inspecting an UI based on 10 rules<br/>- Drafting a design of basic UI layout<br/>- Building paper prototypes or click dummies for user testing<br/>- Learning about prototyping tools, UI animations and history of UI</p> <p>This workshop is proven in many workshops over the last 8 years and regularly updated to match modern standards. Previous attendees rated this workshop with an average score of 9 out of 10.</p> <p>YOUR COACH</p> <p>Thomas Gläser is a passionate product leader who has more than 10 years experience in building successful digital products. He’s working at the intersection of design, business and technology for well-known companies like BMW, Mozilla, Arduino and local startups. Thomas is particularly passionate about helping teams to build better products and executives, to build the right system to support that.</p> <p>He co-founded popular events like push.conference and the UX & Product Meetup in Munich, which unite the local community with global experts in the field. Thomas loves to share his wide-ranging knowledge as a founder, consultant and manager in articles, keynotes and workshops for many years already. In his opinion technology is just a tool to make people happy.</p> <p>YOUR EXTRA BENEFIT</p> <p>All participants will receive a personal 45 minute follow-up call after the training. In this way you can later take up all the questions that have arisen for you in your own application.<br/>YOUR COACH</p> <p>Questions? Get in touch with the workshop host directly: [masked]</p> <p>BOOKING</p> <p>via meetup.com or on Eventbrite (more payment options besides PayPal and team discounts possible)",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1571223250000,
      "duration": 7200000,
      "id": "265709123",
      "name": "Wow yes Early Stage Startups Pitchnight #1 - München",
      "rsvp_limit": 200,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583949600000,
      "local_date": "2020-03-11",
      "local_time": "19:00",
      "updated": 1576671092000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 177,
      "group": {
        "created": 1571221326000,
        "name": "Wow Yes Startups - München",
        "id": 32898396,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "wow-yes-Startups-Munchen",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/wow-yes-Startups-Munchen/events/265709123/",
      "description": "<p>we connect startups with matching investors.</p> <p>Wir laden alle Startups, Investoren und sonstige Interessierte herzlich ein, an diesem Abend dabei zu sein!</p> <p>Fünf spannende Early Stage Startups pitchen ihr Business vor interessierten Investoren und Publikum in München. Wir freuen uns auf einen tollen Abend in entspannter Atmosphäre!</p> <p>Ablauf:</p> <p>Beginn um 19:00 Uhr<br/>Pitch eines erfolgreichen, lokalen Startups<br/>5 Pitches der besten Early Stage Startups<br/>Q&A mit Münchner Investoren und Startup Community<br/>Lokale Jury wählt das Gewinnerstartup des Abends<br/>Networking an der Bar<br/>Ende um 22:00 Uhr</p> <p>Alle Infos zu uns und unseren Events findest Du hier:",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1562151747000,
      "duration": 169200000,
      "id": "262837309",
      "name": "Campus Hackathon München 2020",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1587142800000,
      "local_date": "2020-04-17",
      "local_time": "19:00",
      "updated": 1562151747000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 11,
      "group": {
        "created": 1501244830000,
        "name": "Tech_Hub München",
        "id": 25186228,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Tech_Hub-Munchen",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Tech_Hub-Munchen/events/262837309/",
      "description": "<p>At Campus Hackathon coders, creative developers and designers are working together intensively and under time-pressure hands-on projects. You have 24 hours to convert an idea into code. You already have some ideas? You want to use the tools and platforms you’re familiar with? No problem! The apps can be developed with the backends and frontend technologies you love. We’ll be providing healthy and tasty snacks and meals to keep your mind, body, soul balanced while hacking and you will be supported by experienced mentors of SAP, Finanz Informatik Solutions Plus and mindsquare. You can participate in a group or individually and we match you with another team.</p> <p>Beim Campus Hackathon hast Du 24 Stunden Zeit um eine Idee unter Zeitdruck in Code umzusetzen. Unterstützung bei der Ideenfindung und der Umsetzung erhältst Du von erfahrenen Mentoren unserer Partnerunternehmen. Ein Team besteht idealerweise aus Konzeptern, Programmierern und Webdesignern. Du kannst Dich als Team Log in: oder Dich vor Ort mit anderen zusammentun",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1581937631000,
      "duration": 10800000,
      "id": "268771486",
      "name": "Save the date - Design Thinking Meetup",
      "rsvp_limit": 4,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1584466200000,
      "local_date": "2020-03-17",
      "local_time": "18:30",
      "rsvp_open_offset": "PT177H30M",
      "updated": 1581943001000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 4,
      "group": {
        "created": 1460553553000,
        "name": "Design Thinking München",
        "id": 19836170,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "DT-Muc",
        "who": "Design Thinkers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/DT-Muc/events/268771486/",
      "description": "<p>Save the date for our next DT Meetup!</p> <p>If you are interested to host the next meetup, just drop us a message.</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1574174623000,
      "duration": 7200000,
      "id": "266581534",
      "name": "AfterWERK meets MUNICH STARTUP.de",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1589990400000,
      "local_date": "2020-05-20",
      "local_time": "18:00",
      "updated": 1579073757000,
      "utc_offset": 7200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 21,
      "venue": {
        "id": 26681723,
        "name": "Atelierstraße 29",
        "lat": 48.12380599975586,
        "lon": 11.608274459838867,
        "repinned": true,
        "address_1": "Atelierstraße 29",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1458124246000,
        "name": "WERK1",
        "id": 19716609,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "WERK1munich",
        "who": "movers and shakers",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/WERK1munich/events/266581534/",
      "description": "<p>Once per month, the Munich Startup Community meets at WERK1 for the famous „Feierabend-Bier“, snacks and wine!</p> <p>Join us for 1-2 pitches & networking. If you are interested in pitching yourself, write to [masked].</p> <p>In a nutshell<br/>– Thursday, 20th May 2020 || 6pm<br/>– Informal networking with snacks & drinks<br/>– Meet Munich Entrepreneurs Startups & Freelancers<br/>– max. 2 startup pitches, 4 minutes each</p> ",
      "how_to_find_us": "do somehting",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1582389241000,
      "duration": 3600000,
      "id": "268908409",
      "name": "Webinar: Innovative Lösungen mit dem Design Sprint",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1583254800000,
      "local_date": "2020-03-03",
      "local_time": "18:00",
      "updated": 1582389334000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 23,
      "venue": {
        "id": 26809364,
        "name": "Online",
        "lat": 48.13512420654297,
        "lon": 11.58198070526123,
        "repinned": false,
        "address_1": "Resulting",
        "city": "München",
        "country": "de",
        "localized_country_name": "Germany"
      },
      "group": {
        "created": 1497098231000,
        "name": "München Business Model Design and Innovation Meetup",
        "id": 24388597,
        "join_mode": "open",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Munchen-Business-Model-Design-Innovation-Meetup",
        "who": "Mitglieder",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Munchen-Business-Model-Design-Innovation-Meetup/events/268908409/",
      "description": "<p>Endlose Diskussionen und langwierige Probierschleifen? Das Gestalten von innovativen Lösungsansätzen ist eine komplexe Herausforderung.</p> <p>Wie können Teams Ideen schnell und effizient im Einklang mit den strategischen Zielen weiterentwickeln und testen?</p> <p>Google Entwickler Jake Knapp hat dazu die Methode “Design Sprint” konzeptioniert und in vielen Fällen erfolgreich angewendet.<br/>In nur 4 Tagen designen Teams ein Lösungskonzept und testen die Umsetzung. So können Entwicklungszeiten extrem verkürzt und Risiken reduziert werden.</p> <p>Im Webinar lernst Du die wichtigsten Grundlagen zum Design Sprint:</p> <p>Was ist das Besondere am Design Sprint?<br/>Wie läuft ein Design Sprint?<br/>Wann ist das Format Design Sprint ideal?</p> <p>Achtung, dies ist eine Online-Veranstaltung!</p> <p>Bitte registriere Dich hier, dann erhältst Du den Zugangslink zum virtuellen Webinar-Raum: ",
      "how_to_find_us": "Du erhältst einen Zugangslink zum virtuellen Webinar-Raum.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1580204618000,
      "duration": 7200000,
      "id": "268261986",
      "name": "#3 CareerFoundry Networking Event",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1584036000000,
      "local_date": "2020-03-12",
      "local_time": "19:00",
      "updated": 1582105809000,
      "utc_offset": 3600000,
      "waitlist_count": 0,
      "yes_rsvp_count": 10,
      "group": {
        "created": 1559038025000,
        "name": "Career Foundry Networking",
        "id": 32049396,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "Career-Foundry-Networking",
        "who": "Members",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "link": "https://www.meetup.com/Career-Foundry-Networking/events/268261986/",
      "description": "<p>Hello everybody!<br/>It has been quiet in this group as I had a lot of things to sort out. So first event for this year is up so let's get together and have a great evening. You can talk about your difficulties or why you wanted a career change. Maybe you have questions or would like feedback on your portfolio. Come join us for a mid-week drink and enjoy the evening.</p> <p>Location will be announced soon!</p> ",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "local_time": "13:30",
      "local_date": "2020-03-11",
      "link": "https://www.meetup.com/COKREA/events/267879592/",
      "visibility": "public_limited",
      "group": {
        "created": 1464612571000,
        "name": "COKREA",
        "id": 20012896,
        "join_mode": "approval",
        "lat": 48.13999938964844,
        "lon": 11.579999923706055,
        "urlname": "COKREA",
        "who": "COKREAtors",
        "localized_location": "München, Germany",
        "state": "",
        "country": "de",
        "region": "en_US",
        "timezone": "Europe/Berlin"
      },
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "duration": 10800000,
      "time": 1583929800000,
      "utc_offset": 3600000,
      "name": "Employability & Business Model You - MCBW 2020 Special",
      "id": "267879592"
    }
  ]
};

export {  mockEvents };
