const mockEvents = {
  city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257,
  },
  events: [
    {
      created: 1578507606000,
      duration: 10800000,
      id: "267752688",
      name: "MeasureBowling #12 in Munich",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585245600000,
      local_date: "2020-03-26",
      local_time: "19:00",
      updated: 1578507752000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 12,
      group: {
        created: 1543785470000,
        name: "Analytics Pioneers Munich",
        id: 30635499,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "analytics-pioneers-munich",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/analytics-pioneers-munich/events/267752688/",
      description:
        "<p>--- This is a prepayment event - Tickets: <a href='https://www.xing.com/events/measure-bowling-munich-2020-2355253' class='linkified>https://www.xing.com/events/measure-bowling-munich-2020-2355253</a> ---</p> <p>We are proud to announce that measure bowling will come to munich!</p> <p>The goal of MeasureBowling is to build the Digital Analytics community, both locally and at the global level, with a fun social activity. There are no presentations or talks, just a relaxed evening of bowling.</p> <p>MeasureBowling is organized in 18 cities: Belfast, Berlin, Brussels, Cologne, Dallas, Gdansk, Istanbul, Lyon, Moscow, Munich, Nantes, New York City, Prague, San Francisco, Toronto, Utrecht, Vienna and Würzburg.</p> <p>MeasureBowling is held only once a year, so don’t miss this opportunity to meet the Digital Analytics community in Munich!</p> <p>The ticket for MeasureBowling Munich includes two hours of bowling and a welcome drink.</p> <p>Programm<br/>07:00 PM - Welcome<br/>07:30 PM - Getting ready<br/>08:00 PM - Bowling<br/>10:00 PM - Awarding ceremony + networking</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581637409000,
      duration: 10800000,
      id: "268694342",
      name: "Unternehmertreffen & Start up-Event in München",
      rsvp_limit: 30,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1586102400000,
      local_date: "2020-04-05",
      local_time: "18:00",
      updated: 1581975365000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 29,
      venue: {
        id: 26865352,
        name: "The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München",
        lat: 48.128822326660156,
        lon: 11.574684143066406,
        repinned: false,
        address_1: "Frauenhoferstraße 32, 80469 München",
        city: "München",
        country: "DE",
        localized_country_name: "Germany",
      },
      group: {
        created: 1581635431000,
        name: "Unternehmertreffen and Start up-Event München",
        id: 33341612,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Unternehmertreffen-Start-up-Event-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694342/",
      description:
        "<p>DAS UNTERNEHMERTREFFEN „MÜNCHEN“ STARTUP EVENT</p> <p>INVESTOREN / BUSINESS-ANGEL*<br/>*mehr Details in der Beschreibung</p> <p>Das Unternehmertreffen Munich-Milan ist das Forum für Geschäftsfreunde in ganz Deutschland. Wir hören gemeinsam spannende Vorträge, veranstalten Aktionen, haben Zeit für informelle Gespräche und bahnen Geschäfte an.</p> <p>Wir sind überparteilich und unabhängig. Und vor allem: Wir haben viel Spaß am Netzwerken!</p> <p>Zahlreiche UNTERNEHMER und STARTUP UNTERNEHMEN aus dem Raum München nehmen teil und freuen sich über Jeden, der unser Netzwerk weiter verstärkt. AUCH STUDENTEN MIT GUTEN IDEEN SIND HERZLICH WILLKOMMEN.</p> <p>Informationen und Tickets finden sich unter: <a href='https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-1'>https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-1</a></p> <p>Gerne auch per Telefon: Christian Lenk +49 (0)[masked]</p> <p>Ablauf:<br/>Begrüßung<br/>Kurze Vorstellungsrunde:<br/>- Name, Alter, Herkunft<br/>- Aktuelle Geschäftsbereiche und Projekte</p> <p>Anschließend dürfen 2 freiwillige Unternehmer ihre Geschäfte/ Projekte der Gruppe vorstellen, jeweils circa 15 Minuten.</p> <p>Nach jeder Runde wird eine Unterstützerrunde (Nutzung der Schwarmintelligenz) eingeleitet, wo die Anwesenden für das vorgestellte Projekt zB.:<br/>- Helfende Kontakte zusprechen können<br/>- Ideen zur Förderung des Geschäfts einbringen dürfen<br/>- Selbst Interesse äußern können, um neue Geschäftsbeziehungen anzubahnen.</p> <p>Wenn du einen interessanten Partner kennengelernt hast, könnt ihr eure Visitenkarten austauschen. Diese Runde ist ebenfalls mit 15 Minuten angesetzt.</p> <p>Abschließend wird das Treffen mit einem Referenten aus dem Forex Markt oder Krypto Bereich abgerundet und offen ausgetauscht.</p> <p>Dein Mehrwert<br/>Du lernst jeden Teilnehmer persönlich kennen, wodurch dein Netzwerk sehr schnell wächst. Durch neue Geschäftskontakte und den sich daraus ergebenden Möglichkeiten, kannst du große Umsatzsteigerungen erzielen. Du lernst regionale Geschäftspartner kennen, die, wie auch du, etwas erreichen und schaffen wollen. Gemeinsam könnt ihr eure Ideen schneller und einfacher umsetzen.</p> <p>Informelle Gespräche<br/>Nach dem offiziellen Teil des Unternehmertreffens, in dessen Mittelpunkt die Nutzung der Schwarmintelligenz für die vorgestellten Projekte steht, geht es mit lockerem Netzwerken und viel informellem Austausch weiter. So entstehen echte Geschäftsfreundschaften.</p> <p>Netzwerken<br/>Netzwerke bilden heute die Basis für viele unternehmerische Aktivitäten. Genau dies ist der Grundgedanke von Munich-Milan Wir machen miteinander Geschäfte, unterstützen uns gegenseitig – und haben auch eine Menge Spaß.</p> <p>Melde dich jetzt für Sonntag an und wir sehen uns beim Unternehmertreffen!<br/>Anmelden ist Pflicht: Nach vielen Nachfragen noch der Gästelistelink:<br/><a href='https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-1' class='linkified'>https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-1</a></p> <p>Nur wer die Reservierung für 20,00 Euro bestätigt kann kommen.</p> <p>An der Tür 'The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München' ' bitte die Bestätigung vorzeigen:</p> <p>OHNE TICKET KEIN EINLASS!<br/>Wir freuen uns auf dich und deine Idee</p> <p>INFO INVESTOREN - BUSINESSANGEL:<br/>Wir laden regelmäßig Investoren ein, die sich neue Startup Ideen anschauen. Ein Investor stellt sich nie als Investor vor. Er wird mit dir Kontakt aufnehmen, sollte deine Idee interessant sein!</p>",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581937808000,
      duration: 10800000,
      id: "268771520",
      name: "Save the date - Design Thinking Meetup",
      rsvp_limit: 4,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588091400000,
      local_date: "2020-04-28",
      local_time: "18:30",
      rsvp_open_offset: "PT177H30M",
      updated: 1581943034000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1460553553000,
        name: "Design Thinking München",
        id: 19836170,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "DT-Muc",
        who: "Design Thinkers",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/DT-Muc/events/268771520/",
      description:
        "<p>Save the date for our next DT Meetup!</p> <p>If you are interested to host the next meetup, just drop us a message.</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1583917373000,
      duration: 7200000,
      id: "269345930",
      name: "Trend-Meetup Content & Commerce - All about Affiliate ",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585072800000,
      local_date: "2020-03-24",
      local_time: "19:00",
      updated: 1583944220000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26170711,
        name: "Media Lab Bayern",
        lat: 48.122798919677734,
        lon: 11.605680465698242,
        repinned: true,
        address_1: "Rosenheimer Str. 145C",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1542707415000,
        name: "Mediatrends & Innovation",
        id: 30562336,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "mediatrends_and_innovation",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/mediatrends_and_innovation/events/269345930/",
      description:
        "<p>English version below<br/>----------------------------------</p> <p>Affiliate Marketing ist mit Sicherheit kein neuer Trend, aber nach wie vor begleitet das Thema nahezu jeden Content-Creator.</p> <p>[ADVERTISING] - [Werbung] - [#ad]</p> <p>Immer mehr Kanäle, immer mehr Plattformen gibt es als Content-Spielwiese oder auch Traffic-Treiber für den eigenen Blog oder Content Hub. Doch der Aufwand soll sich lohnen: viele Medienschaffende beschäftigt die Frage, wie sie mit ihrem Content Geld verdienen können.</p> <p>Ab wann ist ein Tool empfehlenswert?<br/>Welche Chancen lasse ich aktuell liegen?<br/>Welche Best Practices gibt es in dem Bereich?</p> <p>Hubert Burda Media hat 2006 tracdelight ins Leben gerufen, um Bloggern und Magazinen ein Tool an die Hand zu geben, ihren Content zu monetarisieren. Heute ist tracdelight ein Tool, was von hochkarätigen Bloggern, wie Farina Opoku (@novalanalove), Jules Villbrandt (@herz.und.blut) und zahlreichen Marken eingesetzt wird. Und deshalb freuen wir uns ganz besonders auf die spannenden Einblicke von Nina Zimmermann, die als Chief Product Officer ganz besondere Insights zum Thema Content &amp; Commerce mitbringt.</p> <p>******<br/>ABLAUF:</p> <p>19:00 - ENTRY</p> <p>19:15 - WELCOME<br/>mit Ronja Rathmann, Media Lab Bayern</p> <p>19:30 - TALK*<br/>mit Nina Zimmermann, Geschäftsführerin &amp; Chief Product Officer, Tracdelight, Hubert Burda Media</p> <p>Ab 20:00 - Q&amp;A Session<br/>mit Networking, Drinks &amp; gemeinsamen Ausklang<br/>******</p> <p>Kommt vorbei! Wir freuen uns auf euch!<br/>Du hast Fragen?<br/>Melde dich bei uns! [masked]</p> <p>Infos zu Nina Zimmermann und Tracdelight:<br/>www.tracdelight.io/<br/>www.burda.com/de/news/mein-grundsatz-lautet-always-stay-humble/</p> <p>* Enthält Produktempfehlungen ;-)</p> <p>Die Veranstaltung findet in deutscher und/oder englischer Sprache statt,<br/>abhängig von den Teilnehmern.</p> <p>------------------------</p> <p>English Version:</p> <p>Affiliate marketing is certainly not a new trend, but the topic still accompanies almost every content creator.</p> <p>[ADVERTISING] - [advertisement] - [#ad]</p> <p>More and more channels, more and more platforms are available as content playgrounds or even traffic drivers for your own blog or content hub. But the effort should be worth it: many media creators are concerned with the question of how they can earn money with their content.</p> <p>When is a tool worth recommending?<br/>Which chances do I currently miss?<br/>What are the best practices in this field?</p> <p>Hubert Burda Media launched tracdelight in 2006 to provide bloggers and magazines with a tool to monetise their content. Today, tracdelight is a tool used by top-class bloggers such as Farina Opoku (@novalanalove), Jules Villbrandt (@herz.und.blut) and numerous brands. And that's why we are especially looking forward to the exciting insights of Nina Zimmermann, who as Chief Product Officer brings very special insights on the topic of Content &amp; Commerce.</p> <p>******<br/>SCHEDULE:<br/>19:00 - ENTRY</p> <p>19:15 - WELCOME<br/>with Ronja Rathmann, Media Lab Bayern</p> <p>19:30 - TALK*<br/>with Nina Zimmermann, Managing Director &amp; Chief Product Officer, Tracdelight, Hubert Burda Media</p> <p>From 20:00 - Q&amp;A SESSION<br/>with networking &amp; drinks<br/>******</p> <p>We're looking forward to seeing you!<br/>If you have any questions, get in touch via [masked]</p> <p>Information about Nina Zimmermann and Tracdelight:<br/>www.tracdelight.io/ (german only)<br/>www.burda.com/en/news/always-stay-humble-s-my-rule/</p> <p>* Contains product recommendations ;-)</p> <p>The event will be held in German and/or English, depending on the participants. Slights might be in German.</p> ",
      how_to_find_us: "6. Stockwerk, Eventspace ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1562151903000,
      duration: 43200000,
      id: "262837346",
      name: "DevCamp - WE PLAY TECH! in München 2020",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585897200000,
      local_date: "2020-04-03",
      local_time: "09:00",
      updated: 1579080662000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      venue: {
        id: 26813258,
        name: "Hochschule München - Campus Lothstraße",
        lat: 48.154300689697266,
        lon: 11.556997299194336,
        repinned: false,
        address_1: "Lothstraße 64",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1501244830000,
        name: "Tech_Hub München",
        id: 25186228,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Tech_Hub-Munchen",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Tech_Hub-Munchen/events/262837346/",
      description:
        "<p>DevCamp is your platform for developers, computer scientists, IT enthusiasts, and those who want to be became them. DevCamp is a conference with an open agenda about the topics that are moving digital minds in 2020. Make new contacts, connect with experts in a relaxed atmosphere and participate in exciting workshops.</p> <p>At DevCamp, you become a co-creator! All sessions will be chosen upfront by the participants, making everyone an active part of the camp. The event is free of charge and cool prizes are awarded for the best sessions. Be part of a whole experience which seamlessly unites the conference with technology.</p> <p>• What to bring<br/>Prepare a session, if you like to participate as a speaker!</p> <p>• Important to know<br/>Register here: <a href='https://www.eventbrite.de/e/devcamp-we-play-tech-in-munchen-2020-tickets-62572197126' class='linkified'>https://www.eventbrite.de/e/devcamp-we-play-tech-in-munchen-2020-tickets-62572197126</a></p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1582655856000,
      duration: 7200000,
      id: "268983616",
      name:
        "Corporate Venturing neu gedacht mit Venture Client - für Startups & Corporates",
      rsvp_limit: 50,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585672200000,
      local_date: "2020-03-31",
      local_time: "18:30",
      updated: 1583744823000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 50,
      venue: {
        id: 26806805,
        name: "Resulting",
        lat: 48.135986328125,
        lon: 11.574705123901367,
        repinned: true,
        address_1: "Rindermarkt 5",
        address_2: "5.Stock",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1497098231000,
        name: "München Business Model Design and Innovation Meetup",
        id: 24388597,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Business-Model-Design-Innovation-Meetup",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Munchen-Business-Model-Design-Innovation-Meetup/events/268983616/",
      description:
        "<p>Startups brauchen Kapital und Coaching. Aber vor allem brauchen sie schon möglichst früh zahlende Kunden. Das funktioniert mit dem Venture Client Modell. Als Venture Client kauft ein Corporate, anstelle von Eigenkapital, das Produkt eines Startups – auch wenn es sich noch in Prototypen-Phase befindet. Mit der Entwicklung der BMW Startup Garage haben die Gründer von 27pilots Corporate Venturing neu erfunden. Das Venture Client Modell nutzt gezielt die strategischen Stärken beider Partner und wurde inzwischen erfolgreich auch in weiteren Konzernen etabliert.</p> <p>Was bedeutet Venture Client für Startups und Corporates und wie unterscheidet sich das Format von Venture Capital?</p> <p>27pilots unterstützt Firmen bei der Einführung von Venture Client Einheiten und der erfolgreichen Skalierung von Startup Projekten. Dr. Maximilian Marquart, Co-Gründer von 27pilots, stellt uns das Venture Client Modell vor und erzählt von Erfolgsbeispielen.</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1579193914000,
      duration: 7200000,
      id: "267965648",
      name: "World Retro Day 2020 @ Agile Munich",
      rsvp_limit: 80,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585157400000,
      local_date: "2020-03-25",
      local_time: "18:30",
      rsvp_open_offset: "PT432H",
      updated: 1584006645000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 68,
      venue: {
        id: 26171276,
        name: "zooplus AG",
        lat: 48.134639739990234,
        lon: 11.566325187683105,
        repinned: true,
        address_1: "Sonnenstr. 31, 80331 ",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1397242023000,
        name: "Agile Munich",
        id: 13860382,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "AgileMunich",
        who: "Agile Practitioners",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/AgileMunich/events/267965648/",
      description:
        "<p>Following your positive feedback from last year, we're bringing back the 'World Retro Day' this year too.</p> <p>World Retrospective Day is a volunteer-based, globally coordinated effort to share in the power of retrospectives. Retrospectives are not just an essential part of the Scrum framework, they are a fundamental practice for any group of people willing to learn from past experiences. It's hard to overestimate the inspiration that can be drawn from pausing to look back, reflecting on what happened and what was possible, and drawing conclusions for the future.</p> <p>For this year's event, we invite you to get hands-on experience with some Liberating Structures and see how the powerful dynamics that these structures can unleash can be adapted to energize and vamp up your retrospectives.</p> <p>We'd like to thank Ilja Vishnevski from Zooplus AG for the initiative to run and facilitate this workshop. Please note that this is a workshop-style event and capacity is limited.</p> <p>IMPORTANT NOTE:<br/>Given the current situation with the Coronavirus we want our agile community, the society and the humanity (:-)) stay safe and healthy.<br/>Therefore we ask you to:</p> <p>- Do not attend our in-person events if in the past 14 days before the start of event you have been to or have been in contact with a person who has been to the high risk regions as identified by RKI (<a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Risikogebiete.html'>https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Risikogebiete.html</a>). These regions as of March 12th also include the whole of Italy and parts of France.<br/>- Do not attend if you feel ill (for any reason)<br/>- During the meetup, observe personal and group hygiene. Remember not to shake hands, etc.</p> <p>We're looking into offering more remote/virtual meetups in near future.</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581340913000,
      duration: 7200000,
      fee: {
        accepts: "paypal",
        amount: 15,
        currency: "EUR",
        description: "",
        label: "Price",
        required: true,
      },
      id: "268602542",
      name: "Structured Creativity #2 - Storytelling Canvas",
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584640800000,
      local_date: "2020-03-19",
      local_time: "19:00",
      updated: 1581698506000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 26756901,
        name: "MUCBOOK CLUBHAUS",
        lat: 48.138675689697266,
        lon: 11.561399459838867,
        repinned: true,
        address_1: "Schillerstr. 3a (Hinterhof)",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1574928701000,
        name: "Structured Creativity - Kreativ- und Innovationsmethoden",
        id: 33055949,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Structured-Creativity-Kreativ-und-Innovationsmethoden",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Structured-Creativity-Kreativ-und-Innovationsmethoden/events/268602542/",
      description:
        "<p>#2: Storytelling Canvas<br/>Bei unserem zweiten Treffen am[masked] lernen wir, Storytelling gezielt einzusetzen und werden in einer Übung überzeugende Geschichten entwickeln.</p> <p>Tickets gibt's über Meetup oder Eventbrite: <a href='https://www.eventbrite.de/e/93930285011' class='linkified'>https://www.eventbrite.de/e/93930285011</a></p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1582019897000,
      duration: 7200000,
      id: "268795784",
      name: "Find your Co-Founder 🚀 Find your Startup! ",
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584035100000,
      local_date: "2020-03-12",
      local_time: "18:45",
      updated: 1583934871000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 100,
      venue: {
        id: 24174998,
        name: "Media Lab Bayern",
        lat: 48.12290954589844,
        lon: 11.60575008392334,
        repinned: true,
        address_1: "Rosenheimer Str. 145 c",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1525869621000,
        name: "Find your Co-Founder / Startup",
        id: 28434245,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Find-your-Co-Founder-or-Startup",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Find-your-Co-Founder-or-Startup/events/268795784/",
      description:
        "<p>English version below<br/>----------------------------------</p> <p>Du möchtest deine Skills zukünftig für ein Projekt nutzen, das dich wirklich überzeugt?<br/>Vielleicht hast du selbst eine Idee für ein Startup und suchst noch Mitstreiter? Oder du bist bereits ein Startup-Gründer und brauchst nun motivierte Kollegen?</p> <p>In welche Kategorie du auch fällst, hier bist du richtig.<br/>Beim 'Find a Co-Founder / Startup' finden Macher zueinander, denn nichts ist so wichtig beim Gründen, wie ein gutes Team.<br/>Teilnehmende Startups stellen ihr Projekt vor und sagen, wen oder was sie suchen, damit im Anschluss die richtigen Leute zueinander finden.</p> <p>Wenn ihr einen Co-Founder sucht und deswegen gern euer Startup vorstellen möchtet, habt ihr die Möglichkeit für einen kurzen Pitch von einer Minute. Dafür müsst ihr ein ausgedruckte Stellenanzeige dabei haben, welche ihr an unsere Jobwall pinnen könnt.</p> <p>WER IMMER GEBRAUCHT WIRD:<br/>- Entwickler<br/>- Designer<br/>- Business Developer<br/>- Journalisten / Texter<br/>- und alle, die einfach Bock haben!</p> <p>ABLAUF:<br/>18:30 - Einlass<br/>19:00 - Begrüßung - Media Lab Bayern<br/>19:05 - Sebastian Di Luzio von Flint.gg<br/>19:15 - Vorstellungsrunde<br/>20:00 - Networking &amp; Free Beer</p> <p>Die Veranstaltung findet in deutscher und/oder englischer Sprache statt,<br/>abhängig von den Teilnehmern.</p> <p>Du hast Fragen?<br/>Melde dich bei uns! [masked]</p> <p>------------------------</p> <p>English Version:</p> <p>Would you like to use your skills in the future for a project that really convinces you?<br/>Maybe you have an idea for a startup yourself and are still looking for a team mate to join you? Or are you already a start-up founder and need motivated colleagues?</p> <p>Whichever category you're in, this is the meetup to go to.<br/>People of action meet at the 'Find a Co-Founder / Startup' because nothing is as important in founding as a good team.</p> <p>If you are looking for a Co-Founder and therefore would like to introduce your start-up, you have the possibility to give a short pitch of one minute. You will need to have a printed job advertisement with you which you can post on our jobwall.</p> <p>WHO IS ALWAYS NEEDED:<br/>- developer<br/>- designer<br/>- business developer<br/>- journalists / copywriters<br/>- and everyone who just loves it!</p> <p>PROCEDURE:<br/>18:30 - Doors open<br/>19:00 - Welcome - Media Lab Bayern<br/>19:05 - Sebastian Di Luzio from Flint.gg<br/>19:15 - Introductory round<br/>20:00 - Networking &amp; free beer</p> <p>The event will be held in German and/or English, depending on the participants.</p> <p>You have questions?<br/>Get in touch via [masked]</p> ",
      how_to_find_us: "6. Stockwerk, Eventspace",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1562750055000,
      duration: 10800000,
      id: "tkqsdrybcgblb",
      name: "Designer-Stammtisch",
      rsvp_limit: 35,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1586365200000,
      local_date: "2020-04-08",
      local_time: "19:00",
      updated: 1562750055000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26506448,
        name: "Cafe Zeitgeist",
        lat: 48.15114212036133,
        lon: 11.576687812805176,
        repinned: false,
        address_1: "Türkenstraße 74",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1444668795000,
        name: "Münchner Designer-Stammtisch",
        id: 19020346,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Designer-Stammtisch",
        who: "Designer",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Designer-Stammtisch/events/tkqsdrybcgblb/",
      description:
        "<p>Liebe DesignerInnen,</p> <p>wir treffen uns jeden 2. Mittwoch im Monat um 19:00 Uhr in (neu:) Zeitgeist in der Türkenstraße.</p> <p>Bringt eure Erfolge, neusten Projekte oder auch kleinen Problemchen mit und teilt sie mit anderen Designern bei einem entspannten Abendessen.</p> <p>Wir freuen uns auf neue Designer und alte Bekannte, und auf einen gemütlichen Abend mit Designer-Kaltsch-und-Tratsch.</p> <p>Lieben Gruß, Ben</p> <p>ps: für alle die gerne länger unterwegs sind finden wir auch diesmal bestimmt wieder eine Location.</p> <p>pps: We mostly chat in German, but English will work just find as well.</p> ",
      how_to_find_us:
        "Fragt nach dem Designerstammtisch dort! *** Please ask for the Designerstammtisch there!",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1582647410000,
      duration: 7200000,
      id: "268979993",
      name: "SRE Republic - Munich",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1588784400000,
      local_date: "2020-05-06",
      local_time: "19:00",
      updated: 1583933746000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 48,
      venue: {
        id: 26055921,
        name: "Personio GmbH",
        lat: 48.14337921142578,
        lon: 11.555990219116211,
        repinned: true,
        address_1: "Rundfunkplatz 4",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1547827354000,
        name: "SRE Republic",
        id: 30954885,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "SRE-Republic",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/SRE-Republic/events/268979993/",
      description:
        "<p>This will be our fourth meetup in the city of Munich and is certain to be another evening of interesting talks around all things SRE, as well as a fantastic opportunity to network with your peers.</p> <p>Date: Wednesday 6th May 2020<br/>Time: 6:30 PM - 9:30 PM<br/>Location: Personio GmbH, Rundfunkplatz 4, 80335 München</p> <p>Doors open for networking @ 6:30</p> <p>Session 1 @ 7:00<br/>Filip Petkovski, Senior Engineer &amp; Pierre Piriou, Senior SRE at Personio<br/>Topic: Enabling Safer Deployments with Gitlab</p> <p>Session 2 @ 7:30<br/>Anthony Moreno, Senior SRE Manager &amp; Boyan Dimitrov, VP of Platform at SIXT<br/>Topic: SRE - from bottom to top and down again</p> <p>Session 3 @ 8:00<br/>To be revealed...</p> <p>More networking and refreshments @ 8:30 - 9:30</p> <p>Looking forward to seeing you there!</p> ",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1583319523000,
      duration: 5400000,
      id: "269178554",
      name:
        "Austausch zu Google G Suite: frag' einen Trainer und Berater alles (online)",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584630000000,
      local_date: "2020-03-19",
      local_time: "16:00",
      updated: 1583949920000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      group: {
        created: 1525793247000,
        name: "Google G Suite Meetup München",
        id: 28424690,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munchen-Google-G-Suite-Meetup",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Munchen-Google-G-Suite-Meetup/events/269178554/",
      description:
        "<p>In einem Hangout Meet beantwortet der G Suite Trainer Holger Ahrens von plus3trainings Eure Fragen rund um das Cloud Office von Google.</p> <p>Gern Anliegen und Themenwünsche vorab hier in den Kommentaren eintragen oder via Google Form unter <a href='https://forms.gle/1LE3u2djCMFQ14NT7' class='linkified'>https://forms.gle/1LE3u2djCMFQ14NT7</a> zusenden.</p> <p>== Link zur Videokonferenz ==</p> <p>Einfach via Hangout Meet dabei sein: <a href='https://meet.google.com/gqb-drpp-xii' class='linkified'>https://meet.google.com/gqb-drpp-xii</a></p> <p>== Ankündigung ==</p> <p>Ein Meetup vor Ort in München am 20.4. ist in Planung: wer möchte da ein Thema vorstellen?</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1583745135000,
      duration: 28800000,
      fee: {
        accepts: "paypal",
        amount: 250,
        currency: "EUR",
        description: "",
        label: "Price",
        required: true,
      },
      id: "269296540",
      name: "Storytelling Innovation Workshop ",
      rsvp_limit: 10,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1587628800000,
      local_date: "2020-04-23",
      local_time: "10:00",
      updated: 1583745612000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26756901,
        name: "MUCBOOK CLUBHAUS",
        lat: 48.138675689697266,
        lon: 11.561399459838867,
        repinned: true,
        address_1: "Schillerstr. 3a (Hinterhof)",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1574928701000,
        name: "Structured Creativity - Kreativ- und Innovationsmethoden",
        id: 33055949,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Structured-Creativity-Kreativ-und-Innovationsmethoden",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Structured-Creativity-Kreativ-und-Innovationsmethoden/events/269296540/",
      description:
        "<p>Storytelling ist eine Kommunikationsform, die erstaunliche Wirkung entfalten kann. Geschichten helfen beim Verstehen, Lernen und Behalten von Wissen, Werten und Botschaften. Sie faszinieren, berühren und dringen trotz medialer Reizüberflutung zu den Menschen durch.</p> <p>Generell ist der Workshop offen für alle mit ersten Vorerfahrungen in Storytelling. Teilnehmer*innen des Storytelling Innovation Workshops vom[masked] erhalten Aufgaben, die an das dort Gelernte anknüpfen.</p> <p>Der Workshop ist optimal für:<br/>Fach- und Führungskräfte, Unternehmer*innen und Selbständige aus allen Bereichen, insbesondere Kommunikation, Marketing, Public Relations, Human Ressources,<br/>… und alle an erfolgreichem Storytelling Interessierten mit ersten eigenen Erfahrungen.</p> <p>Die Trainerin:<br/>Katrin Kuch berät und begleitet Unternehmen dabei, ihre Zielgruppen mit Storytelling und relevanten Inhalten zu erreichen. Sie hat mehr als 12 Jahre Erfahrung in Strategie, Beratung und Konzeption kreativer Kommunikation.<br/>Seit 2016 hält Katrin Kuch Workshops und Vorträge zu Storytelling, Kreativität und digitaler Kommunikation, die sich auszeichnen durch Aktualität, Praxisnähe und innovative Formate angelehnt an Design Thinking, Design Sprint und vielfältige Innovations- und Kreativmethoden.</p> <p>Die Location:<br/>Das MUCBOOK CLUBHAUS ist zentral in der Nähe des Münchner Hauptbahnhofs gelegen und bietet das ideale kreative Umfeld für unseren Workshop. Mehr Infos: <a href='https://www.mucbook.de/clubhaus/' class='linkified'>https://www.mucbook.de/clubhaus/</a></p> <p>Fotos: Bei dem Workshop entstandene Foto- und Videoaufnahmen werden von uns veröffentlicht. Durch die Teilnahme am Workshop erklären Sie sich damit einverstanden.</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1576010173000,
      duration: 30600000,
      id: "267093304",
      name: "Design Sprint Brewery – Bootcamp meets Bierbraukunst",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1585983600000,
      local_date: "2020-04-04",
      local_time: "09:00",
      updated: 1583422848000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 22,
      venue: {
        id: 26891293,
        name: "innosabi GmbH",
        lat: 48.14145278930664,
        lon: 11.599556922912598,
        repinned: true,
        address_1: "Möhlstraße 2",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1483300229000,
        name: "Design Sprint Munich",
        id: 21733865,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "munich-design-sprint",
        who: "Sprinters",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/munich-design-sprint/events/267093304/",
      description:
        "<p>Liebe Sprinter, wir haben da was Frisches für euch 'zusammengebraut' ;)</p> <p>Inspiriert von den Parallelen zwischen dem Design Sprint- und Brau-Prozess haben wir ein 1-Tages-Design Sprint Bootcamp samt Bierbraukurs konzipiert.</p> <p>Wir möchten gemeinsam mit euch Ideation, Prototyping und Testing mit Hopfen, Hefe und Malz mischen, also werdet Teil unseres Experiments 'Design Sprint Brewery'!</p> <p>Das Bootcamp ist kostenpflichtig und die Teilnahme setzt eine Anmeldung über Eventbrite voraus (limitiert auf max. 25 Teilnehmer), daher hier noch ein zusätzliches Schmankerl: als Meetup-Gruppenmitglieder bekommt ihr 10% Rabatt auf die Tickets (Code 'DesignSprintMunich10'):<br/><a href='https://www.eventbrite.de/e/design-sprint-brewery-bootcamp-meets-bierbraukunst-tickets-94231520013?discount=DesignSprintMunichMeetup10' class='linkified'>https://www.eventbrite.de/e/design-sprint-brewery-bootcamp-meets-bierbraukunst-tickets-94231520013?discount=DesignSprintMunichMeetup10</a></p> <p>- - - - - - - - - - - - - - - - - - - - - - - - - - - - -</p> <p>In der Kürze liegt die (Stamm-)würze ;) Hier nochmal alle Informationen:</p> <p>Wir bringen euch die einzelnen Schritte und Methoden des Design Sprints näher, geben praxiserprobte Tipps &amp; Tricks und gehen auf offene Fragen ein. Anhand von kurzen Übungen erlebt ihr aus erster Hand, was es bedeutet, erfolgreich zu sprinten.</p> <p>Zwischen unseren Design Sprint-Sessions werden wir immer wieder Exkurse in die Welt der Bierbraukunst machen und gemeinsam einen kompletten Brauvorgang durchführen.</p> <p>Die 'Design Sprint Brewery' findet am[masked] bei innosabi statt.</p> <p>Leistung:<br/>• Ca. 8 Stunden Design Sprint Bootcamp mit Bierbrau-Exkursen<br/>• Erfahrene Design Sprint Facilitatoren sowie Bierbrauer<br/>• Gesunde Snacks für zwischendurch und mittags, alkoholfreie Getränke<br/>• Aktives Anwenden des Design Sprint Prozesses, von der Herausforderung über Konzepterstellung zu vertesteten Prototypen<br/>• Kennenlernen der Brauanlage<br/>• Interessante Informationen zu Brauprozessen<br/>• Aktives Selberbrauen<br/>• Als Souvenir erhält jeder Teilnehmer eine Flasche selbstgebrautes Bier</p> <p>Deine Coaches:<br/>• Markus Rieger ist Berater für IT, Innovation und Digitalisierung sowie passionierter Hobbybrauer<br/>• Alexander Daamen und Markus Endlein (einige kennen uns ja bereits persönlich ;)) sind Geschäftsführer des Münchner Design Sprint Studios NoPilots und haben bereits zahlreiche Design Sprints in Unternehmen und Startups durchgeführt</p> <p>Perfekt geeignet für:<br/>Startup-Gründer, Führungskräfte, Innovation Leads, Team Leads und Manager, Product Manager / Product Owners, Marketing Manager, UX/UI Designer, Ingenieure und Interessenten am Bierbrauprozess</p> <p>Wichtig:<br/>• Die Veranstaltung wird in der Regel auf Deutsch abgehalten.<br/>• Das Mindestalter ist 18 Jahre.<br/>• Während der Veranstaltung werden wir Bilder und ggf. Videos erstellen und diese über die sozialen Netzwerke teilen. Mit der Anmeldung stimmt ihr der Verwendung und Veröffentlichung zu - vielen Dank.</p> <p>Weitere Informationen und rabattierte Buchung über Eventbrite:<br/><a href='https://www.eventbrite.de/e/design-sprint-brewery-bootcamp-meets-bierbraukunst-tickets-94231520013?discount=DesignSprintMunichMeetup10' class='linkified'>https://www.eventbrite.de/e/design-sprint-brewery-bootcamp-meets-bierbraukunst-tickets-94231520013?discount=DesignSprintMunichMeetup10</a></p> <p>Wir freuen uns auf euch!<br/>Alex &amp; Markus</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      local_time: "19:00",
      local_date: "2020-03-18",
      link: "https://www.meetup.com/innovate-munich/events/269127231/",
      visibility: "public_limited",
      group: {
        created: 1519338318000,
        name: "innovate! Munich",
        id: 27614660,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "innovate-munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      waitlist_count: 0,
      yes_rsvp_count: 23,
      duration: 10800000,
      time: 1584554400000,
      utc_offset: 3600000,
      name:
        "innovate! Munich – wie wir unsere Stadt auf neue Herausforderungen vorbereiten",
      id: "269127231",
    },
    {
      created: 1576227630000,
      duration: 12600000,
      id: "267159156",
      name:
        "Online/Remote & in the Office: Sketch Munich Meetup - Design Systems Edition",
      rsvp_limit: 500,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584639000000,
      local_date: "2020-03-19",
      local_time: "18:30",
      updated: 1583864017000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 262,
      venue: {
        id: 26483775,
        name: "Celonis SE",
        lat: 48.14730453491211,
        lon: 11.57852554321289,
        repinned: true,
        address_1: "Theresienstraße 6",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1482497658000,
        name: "Sketch & Design - Munich",
        id: 21665665,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Sketch-Design-Munich",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Sketch-Design-Munich/events/267159156/",
      description: "Tht's a description ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1574174623000,
      duration: 7200000,
      id: "266581534",
      name: "AfterWERK meets MUNICH STARTUP.de",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1589990400000,
      local_date: "2020-05-20",
      local_time: "18:00",
      updated: 1579073757000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 23,
      venue: {
        id: 26681723,
        name: "Atelierstraße 29",
        lat: 48.12380599975586,
        lon: 11.608274459838867,
        repinned: true,
        address_1: "Atelierstraße 29",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1458124246000,
        name: "WERK1",
        id: 19716609,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "WERK1munich",
        who: "movers and shakers",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/WERK1munich/events/266581534/",
      description:
        "<p>Once per month, the Munich Startup Community meets at WERK1 for the famous „Feierabend-Bier“, snacks and wine!</p> <p>Join us for 1-2 pitches &amp; networking. If you are interested in pitching yourself, write to [masked].</p> <p>In a nutshell<br/>– Thursday, 20th May 2020 || 6pm<br/>– Informal networking with snacks &amp; drinks<br/>– Meet Munich Entrepreneurs Startups &amp; Freelancers<br/>– max. 2 startup pitches, 4 minutes each</p> ",
      how_to_find_us:
        "Access by car only via 'Piusstraße', coming by S-Bahn Ostbahnhof enter Werksviertel on 'Speicherstraße'.",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1581639659000,
      duration: 10800000,
      id: "268694942",
      name: "Unternehmertreffen & Start up-Event in München",
      rsvp_limit: 30,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1591545600000,
      local_date: "2020-06-07",
      local_time: "18:00",
      updated: 1582394104000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26865361,
        name: "The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München",
        lat: 48.128822326660156,
        lon: 11.574684143066406,
        repinned: false,
        address_1: " Frauenhoferstraße 32, 80469 München",
        city: "München",
        country: "DE",
        localized_country_name: "Germany",
      },
      group: {
        created: 1581635431000,
        name: "Unternehmertreffen and Start up-Event München",
        id: 33341612,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Unternehmertreffen-Start-up-Event-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694942/",
      description:
        "<p>DAS UNTERNEHMERTREFFEN „MÜNCHEN“ STARTUP EVENT</p> <p>INVESTOREN / BUSINESS-ANGEL*<br/>*mehr Details in der Beschreibung</p> <p>Das Unternehmertreffen Munich-Milan ist das Forum für Geschäftsfreunde in ganz Deutschland. Wir hören gemeinsam spannende Vorträge, veranstalten Aktionen, haben Zeit für informelle Gespräche und bahnen Geschäfte an.</p> <p>Wir sind überparteilich und unabhängig. Und vor allem: Wir haben viel Spaß am Netzwerken!</p> <p>Zahlreiche UNTERNEHMER und STARTUP UNTERNEHMEN aus dem Raum München nehmen teil und freuen sich über Jeden, der unser Netzwerk weiter verstärkt. AUCH STUDENTEN MIT GUTEN IDEEN SIND HERZLICH WILLKOMMEN.</p> <p>Informationen und Tickets finden sich unter: <a href='https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3' class='linkified'>https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3</a></p> <p>Gerne auch per Telefon: Christian Lenk +49 (0)[masked]</p> <p>Ablauf:<br/>Begrüßung<br/>Kurze Vorstellungsrunde:<br/>- Name, Alter, Herkunft<br/>- Aktuelle Geschäftsbereiche und Projekte</p> <p>Anschließend dürfen 2 freiwillige Unternehmer ihre Geschäfte/ Projekte der Gruppe vorstellen, jeweils circa 15 Minuten.</p> <p>Nach jeder Runde wird eine Unterstützerrunde (Nutzung der Schwarmintelligenz) eingeleitet, wo die Anwesenden für das vorgestellte Projekt zB.:<br/>- Helfende Kontakte zusprechen können<br/>- Ideen zur Förderung des Geschäfts einbringen dürfen<br/>- Selbst Interesse äußern können, um neue Geschäftsbeziehungen anzubahnen.</p> <p>Wenn du einen interessanten Partner kennengelernt hast, könnt ihr eure Visitenkarten austauschen. Diese Runde ist ebenfalls mit 15 Minuten angesetzt.</p> <p>Abschließend wird das Treffen mit einem Referenten aus dem Forex Markt oder Krypto Bereich abgerundet und offen ausgetauscht.</p> <p>Dein Mehrwert<br/>Du lernst jeden Teilnehmer persönlich kennen, wodurch dein Netzwerk sehr schnell wächst. Durch neue Geschäftskontakte und den sich daraus ergebenden Möglichkeiten, kannst du große Umsatzsteigerungen erzielen. Du lernst regionale Geschäftspartner kennen, die, wie auch du, etwas erreichen und schaffen wollen. Gemeinsam könnt ihr eure Ideen schneller und einfacher umsetzen.</p> <p>Informelle Gespräche<br/>Nach dem offiziellen Teil des Unternehmertreffens, in dessen Mittelpunkt die Nutzung der Schwarmintelligenz für die vorgestellten Projekte steht, geht es mit lockerem Netzwerken und viel informellem Austausch weiter. So entstehen echte Geschäftsfreundschaften.</p> <p>Netzwerken<br/>Netzwerke bilden heute die Basis für viele unternehmerische Aktivitäten. Genau dies ist der Grundgedanke von Munich-Milan Wir machen miteinander Geschäfte, unterstützen uns gegenseitig – und haben auch eine Menge Spaß.</p> <p>Melde dich jetzt für Sonntag an und wir sehen uns beim Unternehmertreffen!<br/>Anmelden ist Pflicht: Nach vielen Nachfragen noch der Gästelistelink:<br/><a href='https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3' class='linkified'>https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3</a></p> <p>Nur wer die Reservierung für 20,00 Euro bestätigt kann kommen.</p> <p>An der Tür 'The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München' bitte die Bestätigung vorzeigen:</p> <p>OHNE TICKET KEIN EINLASS!<br/>Wir freuen uns auf dich und deine Idee</p> <p>INFO INVESTOREN - BUSINESSANGEL:<br/>Wir laden regelmäßig Investoren ein, die sich neue Startup Ideen anschauen. Ein Investor stellt sich nie als Investor vor. Er wird mit dir Kontakt aufnehmen, sollte deine Idee interessant sein!</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1582895657000,
      duration: 10800000,
      id: "269059927",
      name: "Afterwork Design Sprint - Innovationskraft in Unternehmen erhöhen",
      rsvp_limit: 25,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584550800000,
      local_date: "2020-03-18",
      local_time: "18:00",
      updated: 1582895657000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      venue: {
        id: 26882447,
        name: "Leopoldstraße 204a",
        lat: 48.174861907958984,
        lon: 11.586097717285156,
        repinned: false,
        address_1: "Leopoldstraße 204a",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1582894287000,
        name: "Blitzminds - Driving Innovation",
        id: 33453825,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Blitzminds-Driving-Innovation",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Blitzminds-Driving-Innovation/events/269059927/",
      description:
        "<p>Du bist Workshop Facilitator, Innovationsmanager, UX Spezialist o.ä. und bist unzufrieden mit der Art und Weise wie Innovationen in deinem Unternehmensumfeld weitergetragen werden? Du kämpfst um Buy-In von Stakeholdern für deine gewonnen Insights und Empfehlungen?</p> <p>Sei Teil unseres abendlichen Design Sprints und finde gemeinsam mit uns heraus wie wir Innovationen in Unternehmen mehr Sichtbarkeit verleihen können, um in weiterer Folge die Innovationskraft zu stärken. Unter der Leitung von Thyra Wegener und Innovationsexperte Cornelius Filbry erarbeiten wir in Sprint Manier konkrete Insights und Umsetzungsmöglichkeiten .</p> <p>Agenda:<br/>18.30 - Begrüßung Cornelius Filbry, Founder Blitzminds GmbH<br/>18.45 - Design Sprint, Thyra Wegener, Founder 10DaysOfDesign<br/>21.00 - Networking, Drinks &amp; Pizza</p> <p>Begrenzte Teilnehmerzahl: Bitte melde dich rechtzeitig an, da wir die Teilnehmerzahl auf 20 Personen beschränken müssen.</p> ",
      how_to_find_us: "Du findest uns @ Timespaces",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1580204618000,
      duration: 7200000,
      id: "268261986",
      name: "#3 CareerFoundry Networking Event",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1584036000000,
      local_date: "2020-03-12",
      local_time: "19:00",
      updated: 1583865018000,
      utc_offset: 3600000,
      waitlist_count: 0,
      yes_rsvp_count: 10,
      venue: {
        id: 17160002,
        name: "Klenze 17",
        lat: 48.13283920288086,
        lon: 11.578277587890625,
        repinned: false,
        address_1: "Klenzestraße 17 80469 München",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      group: {
        created: 1559038025000,
        name: "Career Foundry Networking",
        id: 32049396,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Career-Foundry-Networking",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link:
        "https://www.meetup.com/Career-Foundry-Networking/events/268261986/",
      description:
        "<p>Hello everybody!<br/>It has been quiet in this group as I had a lot of things to sort out. So first event for this year is up so let's get together and have a great evening. You can talk about your difficulties or why you wanted a career change. Maybe you have questions or would like feedback on your portfolio. Come join us for a mid-week drink and enjoy the evening.</p> <p>Location will be announced soon!</p> ",
      visibility: "public",
      member_pay_fee: false,
    },
  ],
};

export { mockEvents };
